name: iOS Build Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          path: Asset-Manager-main

      - name: Debug Folder Structure
        run: ls -R ./Asset-Manager-main

      - name: Select Xcode Version
        run: sudo xcode-select -s /Applications/Xcode_15.0.app

      - name: Install CocoaPods
        run: |
          sudo gem install cocoapods
          pod install
        working-directory: ./Asset-Manager-main

      - name: Build the App
        run: |
          xcodebuild clean build \
            -workspace "Asset Manager.xcworkspace" \
            -scheme "Asset Manager" \
            -sdk iphonesimulator \
            -configuration Debug
        working-directory: ./Asset-Manager-main


      # Optional Step: Run Unit Tests (if you have them)
      # - name: Run Unit Tests
      #   run: |
      #     xcodebuild test \
      #       -workspace "Asset Manager.xcworkspace" \
      #       -scheme "Asset Manager" \
      #       -sdk iphonesimulator \
      #       -destination 'platform=iOS Simulator,name=iPhone 14,OS=latest'
      #   working-directory: ./Asset-Manager-main
