name: iOS Build & Upload to TestFlight (With Committed Pods)

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7

    - name: Install CocoaPods
      run: bundle install && bundle exec pod install

    - name: Build and Archive
      run: xcodebuild -workspace Asset\ Manager.xcworkspace -scheme Asset\ Manager -sdk iphoneos -configuration AppStoreDistribution archive -archivePath ${{github.workspace}}/build/Asset\ Manager.xcarchive -allowProvisioningUpdates

    - name: Export IPA
      run: xcodebuild -exportArchive -archivePath ${{github.workspace}}/build/Asset\ Manager.xcarchive -exportOptionsPlist ExportOptions.plist -exportPath ${{github.workspace}}/build -allowProvisioningUpdates

    - name: Upload to TestFlight
      env:
        APP_STORE_CONNECT_API_KEY: ${{ secrets.APP_STORE_CONNECT_API_KEY }}
        APP_STORE_CONNECT_API_ISSUER: ${{ secrets.APP_STORE_CONNECT_API_ISSUER }}
        APP_STORE_CONNECT_API_KEY_ID: ${{ secrets.APP_STORE_CONNECT_API_KEY_ID }}
      run: bundle exec fastlane upload_to_testflight
